### ISSUE TITLE
TypeError: Stock.tradestats() got an unexpected keyword argument 'date'

### ISSUE THREAD

**Issue by shadowstarser** [WISEPLAT/backtrader_moexalgo#4]
Добрый вечер.
Пробую запустить пример  01 - Symbol.py.
но получаю  ошибку:

C:\Users\tanat\PycharmProjects\moex_candles\.venv\Scripts\python.exe "C:\Users\tanat\PycharmProjects\moex_candles\01 - Symbol.py" 
Авторизуемся на Московской Бирже
Traceback (most recent call last):
  File "C:\Users\tanat\PycharmProjects\moex_candles\01 - Symbol.py", line 74, in <module>
    cerebro.run()  # Запуск торговой системы
    ^^^^^^^^^^^^^
  File "C:\Users\tanat\PycharmProjects\moex_candles\.venv\Lib\site-packages\backtrader\cerebro.py", line 1132, in run
    runstrat = self.runstrategies(iterstrat)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tanat\PycharmProjects\moex_candles\.venv\Lib\site-packages\backtrader\cerebro.py", line 1215, in runstrategies
    data._start()
  File "C:\Users\tanat\PycharmProjects\moex_candles\.venv\Lib\site-packages\backtrader\feed.py", line 203, in _start
    self.start()
  File "C:\Users\tanat\PycharmProjects\moex_candles\.venv\Lib\site-packages\backtrader_moexalgo\moexalgo_feed.py", line 251, in start
    klines, get_live_bars_from = self.get_super_candles(from_date=self.from_date,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tanat\PycharmProjects\moex_candles\.venv\Lib\site-packages\backtrader_moexalgo\moexalgo_feed.py", line 416, in get_super_candles
    iterator = ticker.tradestats(date=last_date, till_date=till_date, limit=self.limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Stock.tradestats() got an unexpected keyword argument 'date'

Подскажите, как избавиться от ошибки.

**Comment by shadowstarser** [comment]
Дополню: OS Windows 11 , Python 3.12.3
(.venv) PS C:\Users\tanat\PycharmProjects\moex_candles> pip list
Package             Version
------------------- -----------
anyio               4.3.0
backtrader          1.9.78.123
backtrader-moexalgo 1.0.9
certifi             2024.2.2
charset-normalizer  3.3.2
contourpy           1.2.1
cycler              0.12.1
fonttools           4.51.0
h11                 0.14.0
httpcore            1.0.5
httpx               0.27.0
idna                3.7
kiwisolver          1.4.5
matplotlib          3.9.0
moexalgo            2.0.3
numpy               1.26.4
packaging           24.0
pandas              2.2.2
pillow              10.3.0
pip                 24.0
pyparsing           3.1.2
python-dateutil     2.9.0.post0
pytz                2024.1
requests            2.31.0
six                 1.16.0
sniffio             1.3.1
tzdata              2024.1
urllib3             2.2.1
websockets          12.0

**Comment by mrals2018** [comment]
День добрый!
Также имею данную ошибку на том же самом примере! Не понимаю как исправить.. Python 3.12.4
Packages:
Package             Version
------------------- -----------
anyio               4.4.0
apimoex             1.4.0
backtrader          1.9.78.123
backtrader-moexalgo 1.0.9
certifi             2024.6.2
cffi                1.16.0
charset-normalizer  3.3.2
contourpy           1.2.1
cryptography        42.0.8
cycler              0.12.1
finplot             1.9.5
fonttools           4.53.0
h11                 0.14.0
httpcore            1.0.5
httpx               0.27.0
idna                3.7
kiwisolver          1.4.5
matplotlib          3.9.0
moexalgo            2.1.1
numpy               2.0.0
packaging           24.1
pandas              2.2.2
pillow              10.4.0
pip                 24.1.1
pycparser           2.22
PyJWT               2.8.0
pyparsing           3.1.2
PyQt6               6.7.0
PyQt6-Qt6           6.7.2
PyQt6-sip           13.6.0
pyqtgraph           0.13.7
python-dateutil     2.9.0.post0
pytz                2024.1
requests            2.32.3
setuptools          70.2.0
six                 1.16.0
sniffio             1.3.1
tzdata              2024.1
urllib3             2.2.2
websockets          12.0
wheel               0.43.0

**Comment by flashus** [comment]
Исправил #5

**Comment by ivan02022000** [comment]
установите пакет Moex algo старой версии в терминале ПК
`pip install moexalgo==1.0.1`

**Comment by WISEPLAT** [comment]
Проверьте ещё раз.
